version: '2'
services:
    rails:
        image: ruby:2.3
        hostname: "${PROJECT_NAME}_rails"
        container_name: "${PROJECT_NAME}_rails"
        ports:
            - "${RAILS_PORT}:3000"
            - 8808:8808
        volumes:
            - "./${PROJECT_ROOT}:/usr/src/app"
        environment:
          RAILS_ENV: "${RAILS_ENV}"
        working_dir: /usr/src/app
        links:
            - postgresql
        entrypoint: ./postinstall.sh

    postgresql:
        image: postgres:9.6
        hostname: "${PROJECT_NAME}_db"
        container_name: "${PROJECT_NAME}_db"
        volumes_from:
            - data
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_DB: "${DB_NAME}"
    data:
        image: postgres:9.6
        hostname: "${PROJECT_NAME}_postgres_data"
        container_name: "${PROJECT_NAME}_postgres_data"
        volumes:
            - /var/lib/postgresql/data
        command: "true"
    redis:
        image: redis
        ports:
            - 6379:6379
    pg-admin:
        image: fenglc/pgadmin4:1.4
        hostname: "${PROJECT_NAME}_pgadmin"
        container_name: "${PROJECT_NAME}_pgadmin"
        ports:
            - 5050:5050
        links:
            - postgresql:postgres
        volumes:
            - /etc/localtime:/etc/localtime
