development:
  adapter: async

docker:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: rkl

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: rokoloca_production
