default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: postgresql

docker:
  <<: *default
  database: rokoloca_docker
  user: rokoloca
  password: password

development:
  <<: *default
  database: rokoloca_development
  user: rokoloca
  password: password

test:
  <<: *default
  database: rokoloca_test
  user: rokoloca
  password: password

production:
  <<: *default
  database: db/production.sqlite3
